### ISSUE TITLE
问：SRS计划引入一个MIT-style授权的项目，是否有影响？

### ISSUE THREAD

**Issue by minghuizhou** [osslab-pku/OpenSourceLicense-FQA#3]
我负责的项目SRS采用[MIT or MulanPSL-2.0](https://github.com/ossrs/srs/blob/develop/LICENSE.DUAL)双协议授权，计划引入一个项目是[MIT-style](https://github.com/c-ares/c-ares)授权的项目？请问这种修改过的MIT协议，是否对项目有影响？它属于BSD还是Apache兼容？ - SRS Maintainer杨同学

**Comment by minghuizhou** [comment]
简单来说，这种情况属于兼容性判定场景。
SRS是MIT or MulanPSL-2.0，如果引入一个新的许可证license-C，那么问题是：
MIT or MulanPSL-2.0 跟 license-C 互相兼容吗？（许可证A兼容许可证C是指，A授权的作品与C授权的作品经过修改或合并，可以使用C对作品的整体进行授权。兼容性是有方向的，A兼容C，但C不一定兼容A。）
一般来说，MIT or MulanPSL-2.0的兼容性很好，跟BSD、MIT类宽松许可证可以互相兼容。（有一些细节差异可以做细节判定。）

关于兼容性判定问题可以参见：
https://github.com/osslab-pku/OpenSourceLicense-FQA/blob/master/open-source-license-fqa.md

**Comment by winlinvip** [comment]
这个项目的协议还不是MIT，而是MIT-style，是否可以认为它是MIT协议呢？

https://github.com/c-ares/c-ares

c-ares is of course distributed under the same MIT-style license as the original ares.

**Comment by minghuizhou** [comment]
所谓MIT-style是指它跟MIT的基本条款一致，例如对其许可的代码的复制、修改、分发几乎没有任何义务。
但是，你不能就认为它就是MIT协议，因为：
1）既然它是MIT-style，它为啥不直接使用MIT呢？着说明它们在细节条款上有差异。
2）MIT是OSI认证的，这有牵引作用。即，人们在自由选择时会倾向于选择MIT而不是类似MIT的协议。

**Comment by winlinvip** [comment]
好的，感谢周教授，我想应该大概可以判断是没问题的，它是MIT类似的。

它没有OSI的认证，它有些MIT的修改也不太明确会是什么问题，也不知道如何遵守它的条款，甚至就连修改了MIT什么条款也不太明确。

不过，应该可以认为肯定没有加入GPL的条款，否则就不能叫MIT-like了，这个差异也太大了。
